guitarcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),

]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('guitars/', views.guitars_index, name='index'),
    path('guitars/<int:guitar_id>/', views.guitars_detail, name='detail'),
    path('guitars/<int:guitar_id>/add_maintenance/', views.add_maintenance, name='add_maintenance'),
    path('guitars/<int:guitar_id>/add_photo/', views.add_photo, name='add_photo'),
    path('guitars/<int:guitar_id>/assoc_strap/<int:strap_id>/', views.assoc_strap, name='assoc_strap'),
    path('guitars/create/', views.GuitarCreate.as_view(), name='guitars_create'),
    path('guitars/<int:pk>/update/', views.GuitarUpdate.as_view(), name='guitars_update'),
    path('guitars/<int:pk>/delete/', views.GuitarDelete.as_view(), name='guitars_delete'),
    path('straps/', views.StrapList.as_view(), name='straps_index'),
    path('straps/<int:pk>/', views.StrapDetail.as_view(), name='straps_detail'),
    path('straps/create/', views.StrapCreate.as_view(), name='straps_create'),
    path('straps/<int:pk>/update/', views.StrapUpdate.as_view(), name='straps_update'),
    path('straps/<int:pk>/delete/', views.StrapDelete.as_view(), name='straps_delete'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date

# Create your models here.
WORK = (
    ('S', 'String Replacement'),
    ('C', 'Cleaning'),
    ('P', 'Part Replacement'),
    ('F', 'Fret Level & Polish'),
    ('A', 'Full Setup'),
)

class Strap(models.Model):
    brand = models.CharField(max_length=50)
    color = models.CharField(max_length=20)
    material = models.CharField(max_length=30)

    def __str__(self):
        return self.brand

    def get_absolute_url(self):
        return reverse('straps_detail', kwargs={'pk': self.id})

class Guitar(models.Model):
    brand = models.CharField(max_length=100)
    model = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    year = models.IntegerField()
    straps = models.ManyToManyField(Strap)


    def __str__(self):
        return self.model
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'guitar_id': self.id})
    
class Photo(models.Model):
    url = models.CharField(max_length=200)
    guitar = models.ForeignKey(Guitar, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for guitar_id: {self.guitar_id} @{self.url}"

class Maintenance(models.Model):
    date = models.DateField('maintenance date')
    
    work = models.CharField(
        max_length=1,
        choices=WORK,
        default=WORK[0][0])

    guitar = models.ForeignKey(Guitar, on_delete=models.CASCADE)

    def __str__(self):
    # Nice method for obtaining the friendly value of a Field.choice
        return f"{self.get_work_display()} on {self.date}"

    class Meta:
        ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Maintenance

class MaintenanceForm(ModelForm):
  class Meta:
    model = Maintenance
    fields = ['date', 'work']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.http import HttpResponse
from .forms import MaintenanceForm
import uuid
import boto3
from .models import Guitar, Strap, Photo

S3_BASE_URL = 'https://s3.us-west-1.amazonaws.com/'
BUCKET = 'guitarcollectorbucket'

# Create your views here.

def add_photo(request, guitar_id):
   
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
       
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
   
        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
       
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            
            Photo.objects.create(url=url, guitar_id=guitar_id)
        except:
            print('An error occurred uploading file to S3')
    return redirect('detail', guitar_id=guitar_id)

class GuitarCreate(CreateView):
    model = Guitar
    fields = ['brand', 'model', 'description', 'year']

class GuitarUpdate(UpdateView):
  model = Guitar
  
  fields = ['brand', 'model', 'description', 'year']

class GuitarDelete(DeleteView):
  model = Guitar
  success_url = '/guitars/'

def home(request):
  return render(request, 'home.html')


def about(request):
    return render(request, 'about.html')

def guitars_index(request):
    guitars = Guitar.objects.all()
    return render(request, 'guitars/index.html', { 'guitars': guitars })

def guitars_detail(request, guitar_id):
    guitar = Guitar.objects.get(id=guitar_id)
    straps_guitar_doesnt_have = Strap.objects.exclude(id__in = guitar.straps.all().values_list('id'))
    maintenance_form = MaintenanceForm()
    return render(request, 'guitars/detail.html', { 
        'guitar': guitar, 'maintenance_form': maintenance_form,
        'straps': straps_guitar_doesnt_have
    
    })

def add_maintenance(request, guitar_id):
  # create a ModelForm instance using the data in request.POST
  form = MaintenanceForm(request.POST)
  # validate the form
  if form.is_valid():
    # don't save the form to the db until it
    # has the cat_id assigned
    new_maintenance = form.save(commit=False)
    new_maintenance.guitar_id = guitar_id
    new_maintenance.save()
  return redirect('detail', guitar_id=guitar_id)

def assoc_strap(request, guitar_id, strap_id):
  Guitar.objects.get(id=guitar_id).straps.add(strap_id)
  return redirect('detail', guitar_id=guitar_id)

class StrapList(ListView):
  model = Strap

class StrapDetail(DetailView):
  model = Strap

class StrapCreate(CreateView):
  model = Strap
  fields = '__all__'

class StrapUpdate(UpdateView):
  model = Strap
  fields = '__all__'

class StrapDelete(DeleteView):
  model = Strap
  success_url = '/straps/'

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

    <h1>About the Guitar Collector</h1>
<hr />
<p>Hire the Guitar Collector!</p>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Guitar Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp;GuitarCollector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'straps_create' %}">Add a Strap</a></li>
          <li><a href="{% url 'straps_index' %}">View All Straps</a></li>
          <li><a href="{% url 'guitars_create' %}">Add a Guitar</a></li>
          <li><a href="{% url 'index' %}">View All My Guitars</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2021 Guitar Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/guitars/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Guitar Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ guitar.model }}</span>
        <p>Brand: {{ guitar.brand }}</p>
        <p>Description: {{ guitar.description }}</p>
        {% if guitar.year > 0 %}
          <p>Year: {{ guitar.year }}</p>
        {% else %}
          <p>Year: Not Provided</p>
        {% endif %}
        <form action="{% url 'add_photo' guitar.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
          {% csrf_token %}
          <input type="file" name="photo-file">
          <br><br>
          <input type="submit" class="btn" value="Upload Photo">
      </form>
      </div>
      <div class="card-action">
        <a href="{% url 'guitars_update' guitar.id %}">Edit</a>
        <a href="{% url 'guitars_delete' guitar.id %}">Delete</a>
      </div>
    </div>
    {% for photo in guitar.photo_set.all %}
      <img class="responsive-img card-panel" src="{{photo.url}}">
    {% empty %}
      <div class="card-panel teal-text center-align">No Photos Uploaded</div>
    {% endfor %}
    
  </div>
  <div class="col s6">
    <form action="{% url 'add_maintenance' guitar.id %}" method="post">
        {% csrf_token %}
        {{ maintenance_form.as_p }}
        <input type="submit" class="btn" value="Add Work">
      </form>
    
    <table class="striped">
      <thead>
        <tr><th>Date</th><th>Maintenance</th></tr>
      </thead>
      <tbody>
        {% for maintenance in guitar.maintenance_set.all %}
          <tr>
            <td>{{maintenance.date}}</td>
            <td>{{maintenance.get_work_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<hr>
<div class="row">
  <div class="col s6">
    <h3>{{ guitar.model }}'s Straps</h3>
    {% if guitar.straps.count %}
      {% for strap in guitar.straps.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              A <span style="color: {{ strap.color }}">{{ strap.color }}</span> {{ strap.brand }} Strap
            </span>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>No Straps added</h5>
    {% endif %}
  </div>
  <!-- Available toys will come after this line -->

<div class="col s6">
  <h3>Available Straps</h3>
  {% if straps.count %}
    {% for strap in straps.all %}
      <div class="card">
        <div class="card-content">
          <span class="card-title">
            A <span style="color: {{ strap.color }}">{{ strap.color }}</span> {{ strap.brand }} Strap
          </span>
        </div>
        <div class="card-action">
          <form action="{% url 'assoc_strap' guitar.id strap.id %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn">Add</button>
          </form>
        </div>
      </div>
    {% endfor %}
  {% else %}
    <h5>This {{guitar.model}} Already Has All Straps Available</h5>
  {% endif %}
  </div>
</div>
<script>
  const dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });
  const selectEl = document.getElementById('id_work');
  M.FormSelect.init(selectEl);
</script>
{% endblock %}

main_app/templates/guitars/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Guitar List</h1>

{% for guitar in guitars %}
  <div class="card">
    <a href="{% url 'detail' guitar.id %}">   
        <div class="card-content">
        <span class="card-title">{{ guitar.model }}</span>
        <p>Brand: {{ guitar.brand }}</p>
        {% if guitar.year > 0 %}
        <p>Year: {{ guitar.year }}</p>
        {% else %}
        <p>Year: Not Provided</p>
        {% endif %}
        <p>Description: {{ guitar.description }}</p>
        </div>
    </a>
  </div>
{% endfor %}

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1 id="home-title">Welcome to Guitar Guitar Collector</h1>
<a href="https://imgur.com/x00epva"><img src="https://i.imgur.com/x00epva.jpg" title="source: imgur.com" />
{% endblock %}

main_app/templates/main_app/guitar_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Guitar</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' guitar.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/guitar_form.html
{% extends 'base.html' %}

{% block content %}
  
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Guitar</h1>
  {% endif %}

<!-- Leaving the action empty makes the form post to the same url used to display it -->
<form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/strap_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Strap</h1>

  <h4>Are you sure you want to delete? <span class="teal-text">{{ object.brand }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'straps_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/strap_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Strap Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ strap.brand }}</span>
        <p>Color: {{ strap.color }}</p>
        <p>Material: {{ strap.material }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'straps_update' strap.id %}">Edit</a>
        <a href="{% url 'straps_delete' strap.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/strap_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.brand}}</span></h1>
  {% else %}
    <h1>Add Strap</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/strap_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Strap List</h1>

{% for strap in strap_list %}
  <a href="{% url 'straps_detail' strap.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ strap.brand }}</span>
            <p>Color: {{ strap.color }}</p>
            <p>Material: {{ strap.material }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}